name: Push to ACR via OIDC

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  move-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Login to ACR
        run: az acr login --name ACRDockerUpload

      - name: Pull and Push
        run: |
          docker pull nginx:latest
          docker tag nginx:latest acrdockerupload.azurecr.io/nginx:v1
          docker push acrdockerupload.azurecr.io/nginx:v1

            # 5. Get the Cluster Context (The "Badge")
      - name: Set AKS Context
        uses: azure/aks-set-context@v3
        with:
          resource-group: 'Github-Azure-RG'
          cluster-name: 'My-AKS-Cluster' # The name of your AKS cluster

      # 6. The "Deployment" (The "Delivery")
      - name: Deploy to Kubernetes
        run: |
          # This command sends your yaml file to the cluster
          kubectl apply -f deployment.yaml
          
          # This forces the cluster to restart the pods with the new image
          kubectl rollout restart deployment/my-web-app

